# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: AGPL-3.0-or-later

min_version = "2026.7.5"

[settings]
experimental = true

[tools]
"aqua:taiki-e/cargo-llvm-cov" = "0.8.7"
"cargo:cargo-about" = "0.8.4"
"github:rust-cross/cargo-zigbuild" = "0.23.4"
gh = "2.96.0"
helm = "4.1.1"
jq = "1.8.2"
rust = { version = "1.97.1", profile = "minimal", components = [ "clippy", "llvm-tools-preview", "rustfmt" ], targets = [ "x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl", "riscv64gc-unknown-linux-musl" ] }
shellcheck = "0.11.0"
zig = "0.15.2"

[task_config]
dir = "{{cwd}}"
includes = [
  "git::https://git.dimidiumlabs.io/platform.git//tasks?ref=340bdf218344fd6b235c402f1d024c1e2446245a",
]

[tasks.fmt]
run = "cargo fmt --all --check"

[tasks.clippy]
run = "cargo clippy --all-targets --all-features -- -D warnings"

[tasks.test]
run = """
cargo build --release
cargo test --all-features --release --locked
"""

[tasks.smoke]
run = "cargo run -p smoke"

[tasks.smoke-local]
run = "./tests/smoke/run-local.sh"

[tasks.coverage]
run = """
mkdir -p target/coverage/
cargo llvm-cov --all-features --workspace --lcov --output-path target/coverage/lcov.info
cargo llvm-cov --all-features --workspace --html --output-dir target/coverage/html
"""
