# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: MPL-2.0

version = 1

[[annotations]]
path = [
    "deploy/charts/pkg-earth/templates/*",
    "src/assets/*",
    "Cargo.lock",
    "mise.lock",
]
SPDX-FileCopyrightText = "2026 Nikolay Govorov"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = ["README.md"]
SPDX-FileCopyrightText = "2026 Nikolay Govorov"
SPDX-License-Identifier = "CC-BY-4.0"
