# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: MPL-2.0

[package]
name = "repos"
version = "0.0.0"
description = "A collection of adapters to external repositories"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
base.workspace = true
dimidiumlabs-config = { git = "https://gilti.dev/platform.git", rev = "06e80eab24180b9f56e8ff1e0182aad60e56f734" }

async-trait.workspace = true
bytes.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
proptest.workspace = true
