# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: MPL-2.0

name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: 2026.7.5
          bootstrap: true
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          shared-key: all-targets
          key: ${{ hashFiles('mise.lock') }}
          cache-on-failure: true
      - run: ./Mirumfile
        env:
          GH_TOKEN: ${{ github.token }}
          PACKAGE_KEY_VERSION: ${{ vars.PACKAGE_KEY_VERSION }}
