# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: MPL-2.0

name: Release

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    concurrency:
      group: release-${{ github.repository }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          version: 2026.7.5
          bootstrap: true
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          shared-key: all-targets
          key: ${{ hashFiles('mise.lock') }}
          cache-on-failure: true
      - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
        with:
          platforms: arm64,riscv64
      - run: ./Mirumfile
        env:
          GH_TOKEN: ${{ github.token }}
          PACKAGE_KEY_VERSION: ${{ vars.PACKAGE_KEY_VERSION }}

          GPG_KEY_ID: ${{ vars.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          APK_PRIVATE_KEY: ${{ secrets.APK_PRIVATE_KEY }}

          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
          S3_PUBLIC_URL: ${{ vars.S3_PUBLIC_URL }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
